[connection]
connection_string = "DefaultEndpointsProtocol=https;AccountName=azdsiodsbcdev;AccountKey=62gIy1bkl1D2atNDMqSv5sKLKMbOQLPlnIifO48qKMz88D+iDE7G1Yg7nlfi4pBQKqCQ89HEtPqv01GWowgzzA==;EndpointSuffix=core.windows.net"
container_name = "historicaliods"

[search]
name_blob = "reject_data/rawdata_2018"
value = "22, 61"
column_filter = "SiteId, PLId"
file_type = "parquet"
path_save_files = "./iods/"
thread_slicing = 1000